persistence:
  enabled: true
  size: 20Gi

resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "4Gi"
    cpu: "2000m"

adminUser:
  user: "admin"
  password: "admin123"
  token: "my-super-secret-auth-token"
  organization: "benchmark"
  bucket: "benchmark"